##SPRING MVC JSP CONFIG
spring.mvc.view.prefix:/
spring.mvc.view.suffix:.jsp
##SPRING DATA MONGODB CONFIG
spring.data.mongodb.uri=${MONGO_URI:}
##FIREBASE CONFIG
FIREBASE_BUCKET_NAME=${BUCKET_NAME:}
FIREBASE_PROJECT_ID=${PROJECT_ID:}
FIREBASE_TYPE=${TYPE:}
FIREBASE_PRIVATE_KEY_ID=${PRIVATE_KEY_ID:}
FIREBASE_PRIVATE_KEY=${PRIVATE_KEY:}
FIREBASE_CLIENT_EMAIL=${CLIENT_EMAIL:}
FIREBASE_CLIENT_ID=${CLIENT_ID:}
FIREBASE_AUTH_URI=${AUTH_URI:}
FIREBASE_TOKEN_URI=${TOKEN_URI:}
FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL:}
FIREBASE_CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL:}

#server.tomcat.additional-tld-skip-patterns=*.jar